In [8]:
from lusidtools.jupyter_tools import toggle_code

"""Structured Results Store for storage of Portfolio data

Attributes
----------
structured_results_store
virtual_document
luminesce
"""

toggle_code("Toggle Docstring")

# Structured Results Store Example

This notebook demostrates loading of a custom Portfolio dataset into the LUSID Structured Results Store.

For more context on what a Structure Result Store/Data is see KB Article <a ref=https://support.lusid.com/knowledgebase/article/KA-01893/en-us>KA-01893</a>

Once loaded, the dataset can be retrieved as one document, or the individual fields accessed

In [9]:
import os
import pandas as pd
from datetime import datetime, timezone
import io
import json
from IPython.core.display import HTML
from itertools import chain

# Then import the key modules from the LUSID package (i.e. The LUSID SDK)
import lusid as lu
import lusid.models as lm

# And use absolute imports to import key functions from Lusid-Python-Tools and other helper package
from lusid.utilities import ApiClientFactory

# Set DataFrame display formats
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.options.display.float_format = "{:,.2f}".format
display(HTML("<style>.container { width:90% !important; }</style>"))

# Authenticate our user and create our API client
secrets_path = os.getenv("FBN_SECRETS_PATH")

api_factory = ApiClientFactory(
    api_secrets_filename=secrets_path,
    app_name="LusidJupyterNotebook",
)

api_status = pd.DataFrame(
    api_factory.build(lu.ApplicationMetadataApi).get_lusid_versions().to_dict()
)

display(api_status)

,api_version,build_version,excel_version,links
0,v0,0.6.9404.0,0.5.2887,"{'relation': 'RequestLogs', 'href': 'http://se..."

In [10]:
srs_api = api_factory.build(lu.StructuredResultDataApi)

<h2>Scope, Effective Date, Result Type</h2>

<ul>
<li>Scope: The scope in which to create or update data maps.</li>
<li>Effective Date: Date at which the structured result is effective from.</li>
<li>Result Type: The Class of the Result, has to be one of [UnitResult/Analytic, UnitResult/Grouped, UnitResult/Holding]</li>
</ul>

In [11]:
scope = "srs" 
effective_date = datetime(2021, 1, 27, tzinfo=timezone.utc)
sample_data_result_type = "UnitResult/Custom"

## Define functions to create the Data Map


<h3>Data Mapping</h3>

The Structured Result Store allows us to upsert structured results, but to give them structure we must first define a Data Mapping,

You can think of a Data Mapping as defining the columns and the column types for each row that gets upserted into the SRS using a specific Data Map

Each "row" can have multiple keys and when difining the data map there are 4 different key types, Unique, PartOfUnique, Leaf, and CompositeLeaf

<h4>Unique</h4>
<blockquote>A primary key that will throw a unique key constraint if multiple equal values are upserted for a single specific result type</blockquote>
<h4>Part of Unique</h4>
<blockquote>A key that will be considered as part of the compoisite primary key for an entity</blockquote>
<h4>Leaf</h4>
<blockquote>Leaf define a value that wont be considered as part of the primary or primary composite key.</blockquote>
<h4>Composite Leaf</h4>
<blockquote>
CompositeLeaf is an abstraction that allows the user to specify which Leafs should be connected, they define data types rather than names of entities as they represent a group of entities.
E.g. If we have an Accural we can define a composite leaf as two leafs of amount and currency
<p></p>
<blockquote>
"UnitResult/Accrual"

DataDefinition(address="UnitResult/Accrual", dataType= "Result0D", keyType="CompositeLeaf") 
</blockquote>

<blockquote>
"UnitResult/Accrual/Amount"

DataDefinition(address="UnitResult/Accrual/Amount", name="Accrual", dataType= "decimal", keyType="Leaf")
</blockquote>
<blockquote>
"UnitResult/Accrual/Ccy"

DataDefinition(address="UnitResult/Accrual/AmountCcy", name="AccrualCcy", dataType= "string", keyType="Leaf")
</blockquote>
</blockquote>

In [12]:
def gen_srs_data_map(leaf_columns, unique_columns, data_types):
    def define_data_definitions(columns, key_type):
        return [lm.DataDefinition(address=f"UnitResult/{scope}/{column}", name=column, data_type=data_types[column], key_type=key_type) 
                      for column in columns]
    data_map = [define_data_definitions(columns, key_type) for columns, key_type in zip((leaf_columns, unique_columns), ("Leaf", "PartOfUnique"))]

    return lm.DataMapping(data_definitions = list(chain(*data_map)))

def create_data_map(df, code, version, leaf_columns, unique_columns, data_types):
    srs_data_map = gen_srs_data_map(leaf_columns, unique_columns, data_types)
    srs_data_map_key = lm.DataMapKey(version=version, code=code)
    
    try:    
        srs_api.create_data_map(
            scope=scope, 
            request_body={
                code: lm.CreateDataMapRequest(
                    id = srs_data_map_key,
                    data = srs_data_map
                )
            }
        )
    except lu.ApiException as e:
        detail = json.loads(e.body)
        if detail['code'] not in [461]: 
            raise e
    return srs_data_map_key

## Read in sample data

In [13]:
df = pd.read_csv("data/srs_custom_data.csv")
df = df.round(0)
display(df.head(5))

    Port Currency      Date  Sys      Value Class
0  PortA      AUD  20210713  FSC   50000000     C
1  PortA      CAD  20210713  FSC  138234286     C
2  PortA      CHF  20210713  FSC     203402     C
3  PortA      EUR  20210713  FSC  235402950     C
4  PortA      EUR  20210715  FTC   22342054     C

## Upsert data into the Structured Results Store

In [14]:
def insert_and_load_data(dataFrame):
    srs_ids=[]
    
    version = "1.01"
    portfolios = dataFrame.groupby("Port")
    unique_columns = ["Currency", "Date", "Sys", "Class"]
    leaf_columns = [column for column in dataFrame.columns if column not in unique_columns]
    
    sample_data_map_key = create_data_map(
        df = df,
        code = 'sample_data_map',
        version = "0.0009",
        leaf_columns = leaf_columns,
        unique_columns = unique_columns,
        data_types = { "RowId": "string", 
                       "Port": "string",
                       "Currency": "string",
                       "Date": "string",
                       "Sys": "string",
                       "Value": "decimal",
                       "Class": "string"}
    )

    for portfolio_id, pf_df in portfolios:    
        srs_id = lm.StructuredResultDataId(
            source = "Client", 
            code = portfolio_id, 
            effective_at = effective_date,
            result_type = sample_data_result_type)
    
        srs_ids.append(srs_id) 
    
        csv_data = io.StringIO()
        pf_df.to_csv(csv_data)   
        
        request_body = {
            portfolio_id: lm.UpsertStructuredResultDataRequest(
                id = srs_id,
                data = lm.StructuredResultData(
                    document_format = "csv",
                    version = version,
                    name = "Data file",
                    document = csv_data.getvalue(),
                    data_map_key = sample_data_map_key
                )
            )
        }
        
        result = srs_api.upsert_structured_result_data(
            scope=scope,
            request_body=request_body)

        display(pd.DataFrame(result.values.items()))
        
    return srs_ids


srs_ids = insert_and_load_data(df)

       0                                1
0  PortA 2022-06-09 17:29:59.849215+00:00

       0                                1
0  PortB 2022-06-09 17:30:00.522850+00:00

       0                                1
0  PortC 2022-06-09 17:30:01.163979+00:00

## Retrieve the raw data from the Structured Results Store

In [15]:
def retrieve_data():
    portfolio_ids = df['Port'].unique()

    for portfolio_id in portfolio_ids:
        srs_id = lm.StructuredResultDataId(
            source = "Client", 
            code = portfolio_id, 
            effective_at = effective_date,
            result_type = sample_data_result_type)
        
        result = srs_api.get_structured_result_data(
            scope = scope, 
            request_body = {
                "key": srs_id
            }
        )
    
        csv_data = io.StringIO(result.values["key"].document)
        doc = pd.read_csv(csv_data)
        display(srs_id.code)
        display(doc)
        
retrieve_data()

'PortA'

    Unnamed: 0   Port Currency      Date  Sys         Value Class
0            0  PortA      AUD  20210713  FSC      50000000     C
1            1  PortA      CAD  20210713  FSC     138234286     C
2            2  PortA      CHF  20210713  FSC        203402     C
3            3  PortA      EUR  20210713  FSC     235402950     C
4            4  PortA      EUR  20210715  FTC      22342054     C
5            5  PortA      EUR  20210727  FTC    2349130942     C
6            6  PortA      EUR  20210812  FTC      23489234     C
7            7  PortA      GBP  20210713  FSC      83425656     C
8            8  PortA      GBP  20210812  FTC      54354564     C
9            9  PortA      JPY  20210713  FSC        654659     C
10          10  PortA      JPY  20210812  FTC        150000     C
11          11  PortA      NOK  20210713  FSC         45645     C
12          12  PortA      NZD  20210713  FSC         65454     C
13          13  PortA      USD  20210713  FSC       -174328     C
14          14  PortA      USD  20210714  FTC         16875     C
15          15  PortA      USD  20210715  FTC        454654     C
16          16  PortA      USD  20210716  FTC  454534135453     C
17          17  PortA      USD  20210719  FTC        534343     C
18          18  PortA      USD  20210723  FTC        101001     C
19          19  PortA      USD  20210726  FTC          4534     C
20          20  PortA      USD  20210727  FTC        544343     C
21          21  PortA      USD  20210729  FTC       3535454     C
22          22  PortA      USD  20210730  FTC         12116     C
23          23  PortA      USD  20210806  FTC      45453435     C
24          24  PortA      USD  20210810  FTC         18406     C
25          25  PortA      USD  20210812  FTC     545343543     B

'PortB'

   Unnamed: 0   Port Currency      Date  Sys         Value Class
0          26  PortB      AUD  20210713  FSC       5590075     B
1          27  PortB      AUD  20210812  FTC       5453435     B
2          28  PortB      SGD  20210713  FSC      43545554     B
3          29  PortB      USD  20210713  FSC  543543435453     B
4          30  PortB      EUR  20210713  FSC      54545435     B

'PortC'

    Unnamed: 0   Port Currency      Date  Sys        Value Class
0           31  PortC      AUD  20210713  FSC     75174369     C
1           32  PortC      AUD  20210715  FTC       261361     C
2           33  PortC      AUD  20210716  FTC        73055     C
3           34  PortC      AUD  20210719  FTC      4161646     C
4           35  PortC      AUD  20210720  FTC    787878787     C
5           36  PortC      AUD  20210722  FTC    878787878     C
6           37  PortC      AUD  20210723  FTC      3349533     C
7           38  PortC      AUD  20210728  FTC      8748787     C
8           39  PortC      AUD  20210812  FTC   4864848616     C
9           40  PortC      CAD  20210713  FSC    854684848     C
10          41  PortC      CAD  20210810  FTC       175973     C
11          42  PortC      CAD  20210812  FTC       298530     C
12          43  PortC      CHF  20210713  FSC         1063     C
13          44  PortC      DKK  20210713  FSC         1042     C
14          45  PortC      EUR  20210713  FSC   -711367480     C
15          46  PortC      EUR  20210809  FTC        77925     C
16          47  PortC      EUR  20210812  FTC       106940     C
17          48  PortC      GBP  20210713  FSC    -51488218     C
18          49  PortC      GBP  20210730  FTC        56250     C
19          50  PortC      HKD  20210713  FSC          599     C
20          51  PortC      JPY  20210713  FSC -17775991002     C
21          52  PortC      JPY  20210812  FTC     26122500     C
22          53  PortC      NOK  20210713  FSC          715     C
23          54  PortC      NZD  20210713  FSC         1091     C
24          55  PortC      SEK  20210713  FSC         1452     C
25          56  PortC      SGD  20210713  FSC         1167     C
26          57  PortC      USD  20210713  FSC   1374469992     C

## Extract a 'Virtual Document' from the Structured Results Store

In [16]:
def retrieve_virtual_document():
    portfolio_ids = df['Port'].unique()

    for portfolio_id in portfolio_ids:
        # Retrieve document from SRS
        srs_id = lm.StructuredResultDataId(
            source = "Client", 
            code = portfolio_id, 
            effective_at = effective_date,
            result_type = sample_data_result_type)
        
        result = srs_api.get_virtual_document(
            scope = scope, 
            request_body = {
                "key": srs_id
            }
        )
        
        # Convert to DataFrame
        result_dfs = []

        for item in result.values["key"].data:
            columns = item.row_data.columns
            values = [i.value for i in item.row_data.values]
    
            row_df = pd.DataFrame(values).T
            row_df.columns = columns
            
            for row in item.row_id.items():            
                row_df[row[0]] = [row[1]]

            result_dfs.append(row_df)
    
        all_dfs = pd.concat(result_dfs)
        
        return all_dfs
        
retrieve_virtual_document()

,UnitResult/srs/Value,UnitResult/srs/Port,UnitResult/srs/Class,UnitResult/srs/Currency,UnitResult/srs/Date,UnitResult/srs/Sys
0,"235,402,950.00",PortA,C,EUR,20210713,FSC
0,"54,354,564.00",PortA,C,GBP,20210812,FTC
0,"45,645.00",PortA,C,NOK,20210713,FSC
0,"-174,328.00",PortA,C,USD,20210713,FSC
0,"50,000,000.00",PortA,C,AUD,20210713,FSC
0,"45,453,435.00",PortA,C,USD,20210806,FTC
0,"83,425,656.00",PortA,C,GBP,20210713,FSC
0,"101,001.00",PortA,C,USD,20210723,FTC
0,"22,342,054.00",PortA,C,EUR,20210715,FTC
0,"12,116.00",PortA,C,USD,20210730,FTC
0,"138,234,286.00",PortA,C,CAD,20210713,FSC
0,"4,534.00",PortA,C,USD,20210726,FTC
0,"3,535,454.00",PortA,C,USD,20210729,FTC
0,"203,402.00",PortA,C,CHF,20210713,FSC
0,"454,654.00",PortA,C,USD,20210715,FTC
0,"545,343,543.00",PortA,B,USD,20210812,FTC
0,"2,349,130,942.00",PortA,C,EUR,20210727,FTC
0,"65,454.00",PortA,C,NZD,20210713,FSC
0,"23,489,234.00",PortA,C,EUR,20210812,FTC
0,"150,000.00",PortA,C,JPY,20210812,FTC
0,"16,875.00",PortA,C,USD,20210714,FTC
0,"544,343.00",PortA,C,USD,20210727,FTC
0,"534,343.00",PortA,C,USD,20210719,FTC
0,"454,534,135,453.00",PortA,C,USD,20210716,FTC
0,"18,406.00",PortA,C,USD,20210810,FTC
0,"654,659.00",PortA,C,JPY,20210713,FSC

In [19]:
import lumipy as lm

secrets_path = os.getenv("FBN_SECRETS_PATH")
atlas = lm.get_atlas(api_secrets_filename=secrets_path)
tv_df = pd.DataFrame([
    {'Scope': scope, 'Code': 'PortA', 'Source': 'Client', 'ResultType': 'UnitResult/Custom', 'EffectiveAt': effective_date},
    {'Scope': scope, 'Code': 'PortB', 'Source': 'Client', 'ResultType': 'UnitResult/Custom', 'EffectiveAt': effective_date},
    {'Scope': scope, 'Code': 'PortC', 'Source': 'Client', 'ResultType': 'UnitResult/Custom', 'EffectiveAt': effective_date},
])

sres = atlas.lusid_unitresult_structuredresult(to_look_up=lm.from_pandas(tv_df))
qry = sres.select('*')

lumi_df = qry.go()
lumi_df

,Scope,Code,Name,Source,ResultType,EffectiveAt,Version,Document,Format,DataMapCode,DataMapVersion,Error
0,srs,PortA,Data file,Client,UnitResult/Custom,2021-01-27,1.01,",Port,Currency,Date,Sys,Value,Class\n0,PortA,A...",Csv,sample_data_map,0.00,NaN
1,srs,PortB,Data file,Client,UnitResult/Custom,2021-01-27,1.01,",Port,Currency,Date,Sys,Value,Class\n26,PortB,...",Csv,sample_data_map,0.00,NaN
2,srs,PortC,Data file,Client,UnitResult/Custom,2021-01-27,1.01,",Port,Currency,Date,Sys,Value,Class\n31,PortC,...",Csv,sample_data_map,0.00,NaN

## Cleanup - delete the data from the Structured Results Store

In [18]:
def delete_data():
    portfolio_ids = df['Port'].unique()

    for portfolio_id in portfolio_ids:
        # Retrieve document from SRS
        srs_id = lm.StructuredResultDataId(
            source = "Client", 
            code = portfolio_id, 
            effective_at = effective_date,
            result_type = sample_data_result_type)
        
        result = srs_api.delete_structured_result_data(
            scope = scope, 
            request_body = {
                "key": srs_id
            }
        )

delete_data()

KeyError: 'Port'